import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createInterface } from 'node:readline';
import type { HandoffReceipt, HarnessCapabilities } from '../../core/types';

interface RpcResponse {
  id?: number | string;
  result?: unknown;
  error?: { code?: number; message?: string; data?: unknown };
  method?: string;
  params?: unknown;
}

export interface CodexProtocolEvent {
  method: string;
  params?: unknown;
}

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject: (error: Error) => void;
  timer: ReturnType<typeof setTimeout>;
}

/** Thin client for the official JSONL app-server protocol generated by this Codex install. */
export class CodexAppServerAdapter {
  private child: ChildProcessWithoutNullStreams | null = null;
  private nextId = 1;
  private pending = new Map<number | string, PendingRequest>();
  private initialized: Promise<string> | null = null;
  private stderr = '';
  private listeners = new Set<(event: CodexProtocolEvent) => void>();

  private ensureProcess(): ChildProcessWithoutNullStreams {
    if (this.child && !this.child.killed) return this.child;
    const child = spawn('codex', ['app-server', '--stdio'], {
      windowsHide: true,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    this.child = child;
    this.stderr = '';
    createInterface({ input: child.stdout }).on('line', (line) => this.onLine(line));
    child.stderr.on('data', (chunk: Buffer) => {
      this.stderr = `${this.stderr}${chunk.toString('utf8')}`.slice(-8_000);
    });
    child.on('exit', (code, signal) => {
      const error = new Error(`Codex app-server exited (${code ?? signal ?? 'unknown'}): ${this.stderr}`);
      for (const request of this.pending.values()) {
        clearTimeout(request.timer);
        request.reject(error);
      }
      this.pending.clear();
      this.child = null;
      this.initialized = null;
    });
    return child;
  }

  private onLine(line: string): void {
    let message: RpcResponse;
    try {
      message = JSON.parse(line) as RpcResponse;
    } catch {
      return;
    }
    if (message.method && message.id === undefined) {
      for (const listener of this.listeners) listener({ method: message.method, params: message.params });
    }
    if (message.id === undefined) return;
    const pending = this.pending.get(message.id);
    if (!pending) return;
    this.pending.delete(message.id);
    clearTimeout(pending.timer);
    if (message.error) {
      pending.reject(new Error(`app-server ${message.error.code ?? 'error'}: ${message.error.message ?? 'unknown error'}`));
    } else {
      pending.resolve(message.result);
    }
  }

  onEvent(listener: (event: CodexProtocolEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private notify(method: string): void {
    this.ensureProcess().stdin.write(`${JSON.stringify({ method })}\n`);
  }

  private request(method: string, params: unknown, timeoutMs = 20_000): Promise<unknown> {
    const id = this.nextId++;
    const child = this.ensureProcess();
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`app-server request timed out: ${method}`));
      }, timeoutMs);
      this.pending.set(id, { resolve, reject, timer });
      child.stdin.write(`${JSON.stringify({ method, id, params })}\n`);
    });
  }

  async initialize(): Promise<string> {
    if (!this.initialized) {
      this.initialized = (async () => {
        const response = await this.request('initialize', {
          clientInfo: { name: 'yunmin-workbench', title: 'Yunmin Workbench', version: '0.1.0' },
          capabilities: {
            experimentalApi: true,
            requestAttestation: false,
          },
        }) as { userAgent?: string };
        if (!response.userAgent) throw new Error('initialize response omitted userAgent');
        this.notify('initialized');
        return response.userAgent;
      })();
    }
    return this.initialized;
  }

  async capabilities(): Promise<HarnessCapabilities> {
    const userAgent = await this.initialize();
    return {
      harness: 'codex',
      canDispatch: true,
      canCreateSession: true,
      canResumeSession: false,
      canObserveRuntime: true,
      canReceiveReceipt: true,
      protocol: 'Codex app-server JSONL v2',
      evidence: `initialize.userAgent=${userAgent}; official thread/start + turn/start and lifecycle notifications`,
    };
  }

  private async startThread(cwd: string, ephemeral: boolean): Promise<{ threadId: string }> {
    await this.initialize();
    const response = await this.request('thread/start', {
      cwd,
      approvalPolicy: 'on-request',
      sandbox: 'workspace-write',
      ephemeral,
      threadSource: 'appServer',
    }) as { thread?: { id?: string } };
    const threadId = response.thread?.id;
    if (!threadId) throw new Error('thread/start response omitted thread.id');
    return { threadId };
  }

  async dispatch(
    intentId: string,
    cwd: string,
    text: string,
    onThreadStarted?: (threadId: string) => void,
  ): Promise<HandoffReceipt> {
    try {
      const { threadId } = await this.startThread(cwd, false);
      onThreadStarted?.(threadId);
      const response = await this.request('turn/start', {
        threadId,
        clientUserMessageId: intentId,
        input: [{ type: 'text', text, text_elements: [] }],
        responsesapiClientMetadata: { source: 'yunmin-workbench', intent_id: intentId },
      }) as { turn?: { id?: string } };
      const turnId = response.turn?.id;
      if (!turnId) throw new Error('turn/start response omitted turn.id');
      return {
        intentId,
        harness: 'codex',
        status: 'ACCEPTED',
        at: new Date().toISOString(),
        runtimeRef: threadId,
        turnRef: turnId,
        source: 'protocol',
        protocolEvidence: 'thread/start.result.thread.id + turn/start.result.turn.id',
      };
    } catch (error) {
      return {
        intentId,
        harness: 'codex',
        status: 'FAILED',
        at: new Date().toISOString(),
        source: 'protocol',
        protocolEvidence: 'Codex app-server request failure',
        message: String(error),
      };
    }
  }

  /** Real protocol smoke without model execution or a durable external session. */
  async smoke(cwd: string): Promise<{ userAgent: string; ephemeralThreadId: string }> {
    const userAgent = await this.initialize();
    const { threadId } = await this.startThread(cwd, true);
    return { userAgent, ephemeralThreadId: threadId };
  }

  close(): void {
    this.child?.kill();
    this.child = null;
    this.initialized = null;
  }
}
