import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createInterface } from 'node:readline';
import type { HandoffReceipt, HarnessCapabilities } from '../../core/types';
import { allowlistedUserAgent, boundedProcessError } from './evidenceBounds';

interface RpcResponse {
  id?: number | string;
  result?: unknown;
  error?: { code?: number; message?: string; data?: unknown };
  method?: string;
  params?: unknown;
}

export interface CodexProtocolEvent {
  method: string;
  /** Present for server-initiated requests such as approval and user input. */
  id?: number | string;
  params?: unknown;
}

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject: (error: Error) => void;
  timer: ReturnType<typeof setTimeout>;
}

export interface CodexAdapterOptions {
  command?: string;
  args?: string[];
  ephemeralDispatch?: boolean;
}

function unavailableCapabilities(reason: string): HarnessCapabilities {
  return {
    harness: 'codex',
    support: {
      dispatch: 'NO', observe: 'NO', receipt: 'NO', approval: 'NO', needsInput: 'NO',
      toolEvents: 'NO', fileEvents: 'NO', externalSessionRef: 'NO', resume: 'NO',
    },
    canDispatch: false,
    canCreateSession: false,
    canResumeSession: false,
    canObserveRuntime: false,
    canReceiveReceipt: false,
    protocol: 'Codex app-server JSONL v2',
    evidence: `unavailable: ${reason}`,
  };
}

/** Thin client for the official JSONL app-server protocol generated by this Codex install. */
export class CodexAppServerAdapter {
  private child: ChildProcessWithoutNullStreams | null = null;
  private nextId = 1;
  private pending = new Map<number | string, PendingRequest>();
  private initialized: Promise<string> | null = null;
  private stderr = '';
  private listeners = new Set<(event: CodexProtocolEvent) => void>();
  private activeThreads = new Set<string>();
  private closing = false;
  private readonly command: string;
  private readonly args: string[];
  private readonly ephemeralDispatch: boolean;

  constructor(options: CodexAdapterOptions = {}) {
    this.command = options.command ?? 'codex';
    this.args = options.args ?? ['app-server', '--stdio'];
    this.ephemeralDispatch = options.ephemeralDispatch ?? false;
  }

  private ensureProcess(): ChildProcessWithoutNullStreams {
    if (this.child) return this.child;
    this.closing = false;
    const child = spawn(this.command, this.args, {
      windowsHide: true,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    this.child = child;
    this.stderr = '';
    // spawn failures (ENOENT, EACCES, ...) surface ONLY as 'error'; without this
    // handler Electron's main process dies with an uncaught-exception dialog.
    child.on('error', (error) => {
      const code = (error as NodeJS.ErrnoException).code ?? 'spawn-failure';
      const wrapped = new Error(`Codex app-server unavailable (${code}): ${error.message}. Is "${this.command}" installed and on PATH?`);
      // Preserve the errno code so capability evidence can carry the allowlisted fact.
      (wrapped as NodeJS.ErrnoException).code = code;
      this.failAllPending(wrapped);
    });
    createInterface({ input: child.stdout }).on('line', (line) => this.onLine(line));
    child.stdout.on('error', () => undefined);
    child.stderr.on('data', (chunk: Buffer) => {
      this.stderr = `${this.stderr}${chunk.toString('utf8')}`.slice(-8_000);
    });
    child.stderr.on('error', () => undefined);
    child.stdin?.on('error', () => undefined);
    child.on('exit', (code, signal) => {
      const error = new Error(`Codex app-server exited (${code ?? signal ?? 'unknown'}): ${this.stderr}`);
      if (!this.closing) {
        for (const threadId of this.activeThreads) {
          this.emit({ method: 'adapter/error', params: { threadId, message: error.message } });
        }
      }
      this.activeThreads.clear();
      this.failAllPending(error);
    });
    return child;
  }

  /** Reject every in-flight request and return to a clean, retryable state. */
  private failAllPending(error: Error): void {
    for (const request of this.pending.values()) {
      clearTimeout(request.timer);
      request.reject(error);
    }
    this.pending.clear();
    this.child = null;
    this.initialized = null;
  }

  private onLine(line: string): void {
    let message: RpcResponse;
    try {
      message = JSON.parse(line) as RpcResponse;
    } catch {
      return;
    }
    if (message.method) {
      this.emit({ method: message.method, id: message.id, params: message.params });
      if (message.method === 'turn/completed') {
        const params = message.params as { threadId?: unknown } | undefined;
        if (typeof params?.threadId === 'string') this.activeThreads.delete(params.threadId);
      }
      return;
    }
    if (message.id === undefined) return;
    const pending = this.pending.get(message.id);
    if (!pending) return;
    this.pending.delete(message.id);
    clearTimeout(pending.timer);
    if (message.error) {
      pending.reject(new Error(`app-server ${message.error.code ?? 'error'}: ${message.error.message ?? 'unknown error'}`));
    } else {
      pending.resolve(message.result);
    }
  }

  onEvent(listener: (event: CodexProtocolEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emit(event: CodexProtocolEvent): void {
    for (const listener of this.listeners) listener(event);
  }

  private notify(method: string): void {
    this.ensureProcess().stdin.write(`${JSON.stringify({ method })}\n`);
  }

  private request(method: string, params: unknown, timeoutMs = 20_000): Promise<unknown> {
    let child: ChildProcessWithoutNullStreams;
    try {
      child = this.ensureProcess();
    } catch (error) {
      return Promise.reject(error instanceof Error ? error : new Error(String(error)));
    }
    return new Promise((resolve, reject) => {
      const id = this.nextId++;
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`app-server request timed out: ${method}`));
      }, timeoutMs);
      this.pending.set(id, { resolve, reject, timer });
      try {
        child.stdin.write(`${JSON.stringify({ method, id, params })}\n`);
      } catch (error) {
        this.pending.delete(id);
        clearTimeout(timer);
        reject(error instanceof Error ? error : new Error(String(error)));
      }
    });
  }

  async initialize(): Promise<string> {
    if (!this.initialized) {
      this.initialized = (async () => {
        const response = await this.request('initialize', {
          clientInfo: { name: 'yunmin-workbench', title: 'Yunmin Workbench', version: '0.1.0' },
          capabilities: {
            experimentalApi: true,
            requestAttestation: false,
          },
        }) as { userAgent?: string };
        if (!response.userAgent) throw new Error('initialize response omitted userAgent');
        const userAgent = allowlistedUserAgent(String(response.userAgent));
        if (!userAgent) throw new Error('initialize response omitted an allowlisted userAgent');
        this.notify('initialized');
        return userAgent;
      })();
    }
    return this.initialized;
  }

  /** Never throws: capability probing must stay a safe, structured answer. */
  async capabilities(): Promise<HarnessCapabilities> {
    try {
      const userAgent = await this.initialize();
      return {
        harness: 'codex',
        support: {
          dispatch: 'YES', observe: 'YES', receipt: 'YES', approval: 'YES', needsInput: 'YES',
          toolEvents: 'YES', fileEvents: 'YES', externalSessionRef: 'YES', resume: 'NO',
        },
        canDispatch: true,
        canCreateSession: true,
        canResumeSession: false,
        canObserveRuntime: true,
        canReceiveReceipt: true,
        protocol: 'Codex app-server JSONL v2',
        evidence: `initialize.userAgent=${userAgent}; official thread/start + turn/start and lifecycle notifications`,
      };
    } catch (error) {
      return unavailableCapabilities(boundedProcessError(error));
    }
  }

  private async startThread(cwd: string, ephemeral: boolean): Promise<{ threadId: string }> {
    await this.initialize();
    const response = await this.request('thread/start', {
      cwd,
      approvalPolicy: 'on-request',
      sandbox: 'workspace-write',
      ephemeral,
      threadSource: 'appServer',
    }) as { thread?: { id?: string } };
    const threadId = response.thread?.id;
    if (!threadId) throw new Error('thread/start response omitted thread.id');
    return { threadId };
  }

  /** Never throws: callers always receive a structured FAILED receipt. */
  async dispatch(
    intentId: string,
    cwd: string,
    text: string,
    onThreadStarted?: (threadId: string) => void,
  ): Promise<HandoffReceipt> {
    try {
      const { threadId } = await this.startThread(cwd, this.ephemeralDispatch);
      onThreadStarted?.(threadId);
      const response = await this.request('turn/start', {
        threadId,
        clientUserMessageId: intentId,
        input: [{ type: 'text', text, text_elements: [] }],
        responsesapiClientMetadata: { source: 'yunmin-workbench', intent_id: intentId },
      }) as { turn?: { id?: string } };
      const turnId = response.turn?.id;
      if (!turnId) throw new Error('turn/start response omitted turn.id');
      this.activeThreads.add(threadId);
      return {
        intentId,
        harness: 'codex',
        status: 'ACCEPTED',
        at: new Date().toISOString(),
        runtimeRef: threadId,
        turnRef: turnId,
        source: 'protocol',
        protocolEvidence: 'thread/start.result.thread.id + turn/start.result.turn.id',
      };
    } catch (error) {
      return {
        intentId,
        harness: 'codex',
        status: 'FAILED',
        at: new Date().toISOString(),
        source: 'protocol',
        protocolEvidence: 'Codex app-server request failure',
        message: String(error),
      };
    }
  }

  /** Real protocol smoke without model execution or a durable external session. */
  async smoke(cwd: string): Promise<{ userAgent: string; ephemeralThreadId: string }> {
    const userAgent = await this.initialize();
    const { threadId } = await this.startThread(cwd, true);
    return { userAgent, ephemeralThreadId: threadId };
  }

  close(): void {
    this.closing = true;
    this.activeThreads.clear();
    this.child?.kill();
    this.failAllPending(new Error('Codex app-server closed'));
  }
}
