import { _electron } from 'playwright';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const overlay = 'E:' + String.fromCharCode(92) + '1project' + String.fromCharCode(92) + 'ai-governance-system';
const stateDir = mkdtempSync(join(tmpdir(), 'wb-peek-'));
const env = Object.fromEntries(Object.entries({ ...process.env, GOV_OVERLAY: overlay, WB_STATE_DIR: stateDir }).filter(([k]) => k !== 'ELECTRON_RUN_AS_NODE'));
const app = await _electron.launch({ args: ['out/main/index.js'], env });
const win = await app.firstWindow();
await win.waitForSelector('.prototype-chrome', { timeout: 60000 });
await win.waitForTimeout(3000);
console.log('BODY-SNIPPET', (await win.evaluate(() => document.body.innerText.slice(0, 400))).replace(/\n/g, ' | '));
await app.close();
